{"type": "error", "data": "Error running pipeline!", "stack": "Traceback (most recent call last):\n  File \"/home/logan/GRAG/graphrag/graphrag/index/run.py\", line 307, in run_pipeline\n    gc.collect()\n  File \"/usr/lib/python3.11/pdb.py\", line 272, in sigint_handler\n    self.set_trace(frame)\n  File \"/usr/lib/python3.11/bdb.py\", line 323, in set_trace\n    def set_trace(self, frame=None):\n    \n  File \"/usr/lib/python3.11/bdb.py\", line 323, in set_trace\n    def set_trace(self, frame=None):\n    \n  File \"/usr/lib/python3.11/bdb.py\", line 92, in trace_dispatch\n    return self.dispatch_call(frame, arg)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.11/bdb.py\", line 137, in dispatch_call\n    if self.quitting: raise BdbQuit\n                      ^^^^^^^^^^^^^\nbdb.BdbQuit\n", "source": "", "details": null}
